spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://localhost:3306/bumingbai?useUnicode=true&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8'
    username: root
    password: root
    druid:
      initial-size: 10
      min-idle: 10
      max-active: 20
      test-while-idle: false
      test-on-return: false
      test-on-borrow: false
      filters: stat
      connection-properties: 'druid.stat.slowSqlMillis=5000'
      validation-query: 'select 1 '
  jpa:
    show-sql: true
    hibernate:
      #create 启动时删数据库中的表，然后创建，退出时不删除数据表
      #create-drop 启动时删数据库中的表，然后创建，退出时删除数据表 如果表不存在报错
      #update 如果启动时表格式不一致则更新表，原有数据保留
      #validate 项目启动表结构进行校验 如果不一致则报错
      ddl-auto: update

logging:
  config: 'classpath:logback/logback-test.xml'
